version: "3"

services:
  app:
    build: .
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
    depends_on:
     - database
    ports:
      - 8000:8000

  database:
    container_name: ee_database_project
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 5432:${POSTGRES_PORT}
