"""essage=Initial

Revision ID: 676127efdea2
Revises:
Create Date: 2022-08-03 01:23:23.772006

"""
import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "676127efdea2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Integer(), primary_key=True, autoincrement=True, unique=True
        ),
        sa.Column("email", sa.String(), primary_key=True, unique=True),
        sa.Column("name", sa.String()),
        sa.Column("password", sa.String()),
        sa.Column("is_company", sa.Boolean()),
        sa.Column("create_at", sa.DateTime(True), default=datetime.datetime.now),
        sa.Column("update_at", sa.DateTime(True), default=datetime.datetime.now),
    )

    op.create_table(
        "Jobs",
        sa.Column(
            "id", sa.Integer(), primary_key=True, autoincrement=True, unique=True
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String()),
        sa.Column("description", sa.String()),
        sa.Column("salary_from", sa.Integer()),
        sa.Column("salary_to", sa.Integer()),
        sa.Column("is_active", sa.Boolean()),
        sa.Column("create_at", sa.DateTime(True), default=datetime.datetime.now),
        sa.Column("update_at", sa.DateTime(True), default=datetime.datetime.now),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("Jobs")
    # ### end Alembic commands ###
